"""Auto-generated cffi declarations for obs.dll. Do not edit."""

PREAMBLE = """
    /* Opaque struct types referenced by extracted signatures */
    struct audio_convert_info;
    struct audio_output_info;
    struct axisang;
    struct dstr;
    struct gs_device_loss;
    struct gs_effect_param_info;
    struct gs_monitor_info;
    struct gs_rect;
    struct gs_shader_param_info;
    struct gs_vb_data;
    struct matrix3;
    struct matrix4;
    struct media_frames_per_second;
    struct obs_audio_info2;
    struct obs_cmdline_args;
    struct obs_encoder_info;
    struct obs_hotkeys_translations;
    struct obs_key_event;
    struct obs_module_failure_info;
    struct obs_mouse_event;
    struct obs_output_info;
    struct obs_scene_item;
    struct obs_sceneitem_order_info;
    struct obs_service_info;
    struct obs_service_resolution;
    struct obs_source_audio;
    struct obs_source_audio_mix;
    struct obs_source_cea_708;
    struct obs_source_frame;
    struct obs_source_frame2;
    struct obs_source_info;
    struct quat;
    struct vec3;
    struct vec4;
    struct video_frame;
    struct video_output_info;

    /* Opaque enums (treated as int) */
    typedef int gs_blend_op_type_enum_stub; /* enum gs_blend_op_type */
    typedef int gs_blend_type_enum_stub; /* enum gs_blend_type */
    typedef int gs_color_space_enum_stub; /* enum gs_color_space */
    typedef int gs_cull_mode_enum_stub; /* enum gs_cull_mode */
    typedef int gs_depth_test_enum_stub; /* enum gs_depth_test */
    typedef int gs_draw_mode_enum_stub; /* enum gs_draw_mode */
    typedef int gs_image_alpha_mode_enum_stub; /* enum gs_image_alpha_mode */
    typedef int gs_index_type_enum_stub; /* enum gs_index_type */
    typedef int gs_stencil_op_type_enum_stub; /* enum gs_stencil_op_type */
    typedef int gs_stencil_side_enum_stub; /* enum gs_stencil_side */
    typedef int gs_texture_type_enum_stub; /* enum gs_texture_type */
    typedef int obs_allow_direct_render_enum_stub; /* enum obs_allow_direct_render */
    typedef int obs_button_type_enum_stub; /* enum obs_button_type */
    typedef int obs_data_number_type_enum_stub; /* enum obs_data_number_type */
    typedef int obs_editable_list_type_enum_stub; /* enum obs_editable_list_type */
    typedef int obs_group_type_enum_stub; /* enum obs_group_type */
    typedef int obs_module_load_state_enum_stub; /* enum obs_module_load_state */
    typedef int obs_obj_type_enum_stub; /* enum obs_obj_type */
    typedef int obs_order_movement_enum_stub; /* enum obs_order_movement */
    typedef int obs_source_type_enum_stub; /* enum obs_source_type */
    typedef int obs_task_type_enum_stub; /* enum obs_task_type */
    typedef int obs_text_info_type_enum_stub; /* enum obs_text_info_type */
    typedef int obs_transition_scale_type_enum_stub; /* enum obs_transition_scale_type */
    typedef int obs_transition_target_enum_stub; /* enum obs_transition_target */

    /* Opaque typedefs ending in _t */
    typedef struct add_window_cb_s *add_window_cb;
    typedef struct audio_input_callback_s *audio_input_callback_t;
    typedef struct audio_resampler_s *audio_resampler_t;
    typedef struct bitmap_callbacks_s *bitmap_callbacks;
    typedef struct bitmap_create_s *bitmap_create;
    typedef struct cf_token_array_s *cf_token_array_t;
    typedef struct config_s *config_t;
    typedef struct device_luid_cb_s *device_luid_cb;
    typedef struct display_s *display;
    typedef struct encoded_callback_s *encoded_callback_t;
    typedef struct ep_param_array_s *ep_param_array_t;
    typedef struct ep_var_array_s *ep_var_array_t;
    typedef struct gif_bitmap_cb_create_s *gif_bitmap_cb_create;
    typedef struct gif_bitmap_cb_destroy_s *gif_bitmap_cb_destroy;
    typedef struct gif_bitmap_cb_get_buffer_s *gif_bitmap_cb_get_buffer;
    typedef struct gif_bitmap_cb_modified_s *gif_bitmap_cb_modified;
    typedef struct gif_bitmap_cb_set_opaque_s *gif_bitmap_cb_set_opaque;
    typedef struct gif_bitmap_cb_test_opaque_s *gif_bitmap_cb_test_opaque;
    typedef struct gif_result_s *gif_result;
    typedef struct global_signal_callback_s *global_signal_callback_t;
    typedef struct graphics_s *graphics_t;
    typedef struct gs_device_s *gs_device_t;
    typedef struct gs_duplicator_s *gs_duplicator_t;
    typedef struct gs_effect_param_array_s *gs_effect_param_array_t;
    typedef struct gs_effect_s *gs_effect_t;
    typedef struct gs_eparam_s *gs_eparam_t;
    typedef struct gs_epass_s *gs_epass_t;
    typedef struct gs_image_file2_s *gs_image_file2_t;
    typedef struct gs_image_file3_s *gs_image_file3_t;
    typedef struct gs_image_file4_s *gs_image_file4_t;
    typedef struct gs_image_file_s *gs_image_file_t;
    typedef struct gs_indexbuffer_s *gs_indexbuffer_t;
    typedef struct gs_samplerstate_s *gs_samplerstate_t;
    typedef struct gs_shader_s *gs_shader_t;
    typedef struct gs_sparam_s *gs_sparam_t;
    typedef struct gs_stagesurf_s *gs_stagesurf_t;
    typedef struct gs_sync_s *gs_sync_t;
    typedef struct gs_technique_s *gs_technique_t;
    typedef struct gs_texrender_s *gs_texrender_t;
    typedef struct gs_timer_range_s *gs_timer_range_t;
    typedef struct gs_timer_s *gs_timer_t;
    typedef struct gs_vertbuffer_s *gs_vertbuffer_t;
    typedef struct gs_zstencil_s *gs_zstencil_t;
    typedef struct input_s *input_t;
    typedef struct log_handler_s *log_handler_t;
    typedef struct lookup_s *lookup_t;
    typedef struct media_remux_job_s *media_remux_job_t;
    typedef struct obs_canvas_s *obs_canvas_t;
    typedef struct obs_destroy_cb_s *obs_destroy_cb;
    typedef struct obs_encoder_group_s *obs_encoder_group_t;
    typedef struct obs_enum_audio_device_cb_s *obs_enum_audio_device_cb;
    typedef struct obs_enum_module_callback_s *obs_enum_module_callback_t;
    typedef struct obs_fader_conversion_s *obs_fader_conversion_t;
    typedef struct obs_find_module_callback2_s *obs_find_module_callback2_t;
    typedef struct obs_find_module_callback_s *obs_find_module_callback_t;
    typedef struct obs_hotkey_active_func_s *obs_hotkey_active_func;
    typedef struct obs_hotkey_atomic_update_func_s *obs_hotkey_atomic_update_func;
    typedef struct obs_hotkey_binding_enum_func_s *obs_hotkey_binding_enum_func;
    typedef struct obs_hotkey_binding_s *obs_hotkey_binding_t;
    typedef struct obs_hotkey_callback_router_func_s *obs_hotkey_callback_router_func;
    typedef struct obs_hotkey_pair_id_s *obs_hotkey_pair_id;
    typedef struct obs_hotkey_pair_s *obs_hotkey_pair_t;
    typedef struct obs_hotkey_registerer_s *obs_hotkey_registerer_t;
    typedef struct obs_hotkeys_platform_s *obs_hotkeys_platform_t;
    typedef struct obs_missing_file_cb_s *obs_missing_file_cb;
    typedef struct obs_missing_file_s *obs_missing_file_t;
    typedef struct obs_missing_files_s *obs_missing_files_t;
    typedef struct obs_module_metadata_s *obs_module_metadata_t;
    typedef struct obs_module_s *obs_module_t;
    typedef struct obs_object_s *obs_object_t;
    typedef struct obs_property_clicked_s *obs_property_clicked_t;
    typedef struct obs_property_modified2_s *obs_property_modified2_t;
    typedef struct obs_property_modified_s *obs_property_modified_t;
    typedef struct obs_save_source_filter_cb_s *obs_save_source_filter_cb;
    typedef struct obs_scene_atomic_update_func_s *obs_scene_atomic_update_func;
    typedef struct obs_source_caption_s *obs_source_caption_t;
    typedef struct obs_source_info_array_s *obs_source_info_array_t;
    typedef struct obs_task_handler_s *obs_task_handler_t;
    typedef struct obs_task_s *obs_task_t;
    typedef struct obs_transition_audio_mix_callback_s *obs_transition_audio_mix_callback_t;
    typedef struct obs_transition_video_render_callback_s *obs_transition_video_render_callback_t;
    typedef struct obs_view_s *obs_view_t;
    typedef struct obs_weak_canvas_s *obs_weak_canvas_t;
    typedef struct obs_weak_encoder_s *obs_weak_encoder_t;
    typedef struct obs_weak_object_s *obs_weak_object_t;
    typedef struct obs_weak_output_s *obs_weak_output_t;
    typedef struct obs_weak_service_s *obs_weak_service_t;
    typedef struct obs_weak_source_s *obs_weak_source_t;
    typedef struct os_cpu_usage_info_s *os_cpu_usage_info_t;
    typedef struct os_dir_s *os_dir_t;
    typedef struct os_event_s *os_event_t;
    typedef struct os_glob_s *os_glob_t;
    typedef struct os_inhibit_s *os_inhibit_t;
    typedef struct os_performance_token_s *os_performance_token_t;
    typedef struct os_proc_memory_usage_s *os_proc_memory_usage_t;
    typedef struct os_process_args_s *os_process_args_t;
    typedef struct os_process_pipe_s *os_process_pipe_t;
    typedef struct os_sem_s *os_sem_t;
    typedef struct os_task_queue_s *os_task_queue_t;
    typedef struct os_task_s *os_task_t;
    typedef struct pass_shaderparam_array_s *pass_shaderparam_array_t;
    typedef struct proc_handler_proc_s *proc_handler_proc_t;
    typedef struct profiler_entry_enum_func_s *profiler_entry_enum_func;
    typedef struct profiler_name_filter_func_s *profiler_name_filter_func;
    typedef struct profiler_name_store_s *profiler_name_store_t;
    typedef struct profiler_snapshot_entry_s *profiler_snapshot_entry_t;
    typedef struct profiler_snapshot_s *profiler_snapshot_t;
    typedef struct profiler_time_entries_s *profiler_time_entries_t;
    typedef struct profiler_time_entry_s *profiler_time_entry_t;
    typedef struct tick_avg_s *tick_avg;
    typedef struct util_uint128_s *util_uint128_t;
    typedef struct video_scaler_s *video_scaler_t;
"""

AUTO_DECLS = """
    bool audio_output_active(const audio_t *audio);
    void audio_output_close(audio_t *audio);
    bool audio_output_connect(audio_t *video, size_t mix_idx, const struct audio_convert_info *conversion, audio_output_callback_t callback, void *param);
    void audio_output_disconnect(audio_t *video, size_t mix_idx, audio_output_callback_t callback, void *param);
    size_t audio_output_get_block_size(const audio_t *audio);
    size_t audio_output_get_channels(const audio_t *audio);
    size_t audio_output_get_planes(const audio_t *audio);
    uint32_t audio_output_get_sample_rate(const audio_t *audio);
    int audio_output_open(audio_t **audio, struct audio_output_info *info);
    bool calldata_get_data(const calldata_t *data, const char *name, void *out, size_t size);
    void calldata_set_data(calldata_t *data, const char *name, const void *in, size_t new_size);
    void gs_begin_frame(void);
    void gs_begin_scene(void);
    void gs_blend_function(enum gs_blend_type src, enum gs_blend_type dest);
    void gs_blend_function_separate(enum gs_blend_type src_c, enum gs_blend_type dest_c, enum gs_blend_type src_a, enum gs_blend_type dest_a);
    void gs_blend_op(enum gs_blend_op_type op);
    void gs_blend_state_pop(void);
    void gs_blend_state_push(void);
    bool gs_can_adapter_fast_clear(void);
    void gs_clear(uint32_t clear_flags, const struct vec4 *color, float depth, uint8_t stencil);
    void gs_color(uint32_t color);
    void gs_color4v(const struct vec4 *v);
    void gs_copy_texture(gs_texture_t *dst, gs_texture_t *src);
    void gs_copy_texture_region(gs_texture_t *dst, uint32_t dst_x, uint32_t dst_y, gs_texture_t *src, uint32_t src_x, uint32_t src_y, uint32_t src_w, uint32_t src_h);
    int gs_create(graphics_t **graphics, const char *module, uint32_t adapter);
    void gs_cubetexture_destroy(gs_texture_t *cubetex);
    enum gs_color_format gs_cubetexture_get_color_format(const gs_texture_t *cubetex);
    uint32_t gs_cubetexture_get_size(const gs_texture_t *cubetex);
    void gs_cubetexture_set_image(gs_texture_t *cubetex, uint32_t side, const void *data, uint32_t linesize, bool invert);
    void gs_debug_marker_begin(const float color[4], const char *markername);
    void gs_debug_marker_begin_format(const float color[4], const char *format, ...);
    void gs_debug_marker_end(void);
    void gs_depth_function(enum gs_depth_test test);
    void gs_destroy(graphics_t *graphics);
    void gs_draw(enum gs_draw_mode draw_mode, uint32_t start_vert, uint32_t num_verts);
    void gs_draw_cube_backdrop(gs_texture_t *cubetex, const struct quat *rot, float left, float right, float top, float bottom, float znear);
    void gs_draw_quadf(gs_texture_t *tex, uint32_t flip, float width, float height);
    void gs_draw_sprite(gs_texture_t *tex, uint32_t flip, uint32_t width, uint32_t height);
    void gs_draw_sprite_subregion(gs_texture_t *tex, uint32_t flip, uint32_t x, uint32_t y, uint32_t cx, uint32_t cy);
    void gs_duplicator_destroy(gs_duplicator_t *duplicator);
    enum gs_color_space gs_duplicator_get_color_space(gs_duplicator_t *duplicator);
    int gs_duplicator_get_monitor_index(void *monitor);
    float gs_duplicator_get_sdr_white_level(gs_duplicator_t *duplicator);
    bool gs_duplicator_update_frame(gs_duplicator_t *duplicator);
    void gs_effect_destroy(gs_effect_t *effect);
    size_t gs_effect_get_default_val_size(gs_eparam_t *param);
    size_t gs_effect_get_num_params(const gs_effect_t *effect);
    void gs_effect_get_param_info(const gs_eparam_t *param, struct gs_effect_param_info *info);
    size_t gs_effect_get_val_size(gs_eparam_t *param);
    bool gs_effect_loop(gs_effect_t *effect, const char *name);
    void gs_effect_set_bool(gs_eparam_t *param, bool val);
    void gs_effect_set_color(gs_eparam_t *param, uint32_t argb);
    void gs_effect_set_default(gs_eparam_t *param);
    void gs_effect_set_float(gs_eparam_t *param, float val);
    void gs_effect_set_int(gs_eparam_t *param, int val);
    void gs_effect_set_matrix4(gs_eparam_t *param, const struct matrix4 *val);
    void gs_effect_set_next_sampler(gs_eparam_t *param, gs_samplerstate_t *sampler);
    void gs_effect_set_texture(gs_eparam_t *param, gs_texture_t *val);
    void gs_effect_set_texture_srgb(gs_eparam_t *param, gs_texture_t *val);
    void gs_effect_set_val(gs_eparam_t *param, const void *val, size_t size);
    void gs_effect_set_vec2(gs_eparam_t *param, const struct vec2 *val);
    void gs_effect_set_vec3(gs_eparam_t *param, const struct vec3 *val);
    void gs_effect_set_vec4(gs_eparam_t *param, const struct vec4 *val);
    void gs_effect_update_params(gs_effect_t *effect);
    void gs_enable_blending(bool enable);
    void gs_enable_color(bool red, bool green, bool blue, bool alpha);
    void gs_enable_depth_test(bool enable);
    void gs_enable_framebuffer_srgb(bool enable);
    void gs_enable_stencil_test(bool enable);
    void gs_enable_stencil_write(bool enable);
    void gs_end_scene(void);
    void gs_enter_context(graphics_t *graphics);
    void gs_enum_adapters(bool (*callback)(void *param, const char *name, uint32_t id), void *param);
    void gs_flush(void);
    bool gs_framebuffer_srgb_enabled(void);
    void gs_frustum(float left, float right, float top, float bottom, float znear, float zfar);
    bool gs_gdi_texture_available(void);
    uint32_t gs_get_adapter_count(void);
    enum gs_color_space gs_get_color_space(void);
    enum gs_cull_mode gs_get_cull_mode(void);
    int gs_get_device_type(void);
    bool gs_get_duplicator_monitor_info(int monitor_idx, struct gs_monitor_info *monitor_info);
    uint64_t gs_get_gpu_dmem(void);
    uint64_t gs_get_gpu_smem(void);
    uint32_t gs_get_height(void);
    bool gs_get_linear_srgb(void);
    void gs_get_size(uint32_t *x, uint32_t *y);
    enum gs_texture_type gs_get_texture_type(const gs_texture_t *texture);
    void gs_get_viewport(struct gs_rect *rect);
    uint32_t gs_get_width(void);
    void gs_image_file2_init(gs_image_file2_t *if2, const char *file);
    bool gs_image_file2_tick(gs_image_file2_t *if2, uint64_t elapsed_time_ns);
    void gs_image_file2_update_texture(gs_image_file2_t *if2);
    void gs_image_file3_init(gs_image_file3_t *if3, const char *file, enum gs_image_alpha_mode alpha_mode);
    bool gs_image_file3_tick(gs_image_file3_t *if3, uint64_t elapsed_time_ns);
    void gs_image_file3_update_texture(gs_image_file3_t *if3);
    void gs_image_file4_init(gs_image_file4_t *if4, const char *file, enum gs_image_alpha_mode alpha_mode);
    bool gs_image_file4_tick(gs_image_file4_t *if4, uint64_t elapsed_time_ns);
    void gs_image_file4_update_texture(gs_image_file4_t *if4);
    void gs_image_file_free(gs_image_file_t *image);
    void gs_image_file_init(gs_image_file_t *image, const char *file);
    void gs_image_file_init_texture(gs_image_file_t *image);
    bool gs_image_file_tick(gs_image_file_t *image, uint64_t elapsed_time_ns);
    void gs_image_file_update_texture(gs_image_file_t *image);
    void gs_indexbuffer_destroy(gs_indexbuffer_t *indexbuffer);
    void gs_indexbuffer_flush(gs_indexbuffer_t *indexbuffer);
    void gs_indexbuffer_flush_direct(gs_indexbuffer_t *indexbuffer, const void *data);
    size_t gs_indexbuffer_get_num_indices(const gs_indexbuffer_t *indexbuffer);
    enum gs_index_type gs_indexbuffer_get_type(const gs_indexbuffer_t *indexbuffer);
    bool gs_is_monitor_hdr(void *monitor);
    bool gs_is_present_ready(void);
    void gs_leave_context(void);
    void gs_load_default_samplerstate(bool b_3d, int unit);
    void gs_load_indexbuffer(gs_indexbuffer_t *indexbuffer);
    void gs_load_pixelshader(gs_shader_t *pixelshader);
    void gs_load_samplerstate(gs_samplerstate_t *samplerstate, int unit);
    void gs_load_swapchain(gs_swapchain_t *swapchain);
    void gs_load_texture(gs_texture_t *tex, int unit);
    void gs_load_vertexbuffer(gs_vertbuffer_t *vertbuffer);
    void gs_load_vertexshader(gs_shader_t *vertshader);
    void gs_matrix_get(struct matrix4 *dst);
    void gs_matrix_identity(void);
    void gs_matrix_mul(const struct matrix4 *matrix);
    void gs_matrix_pop(void);
    void gs_matrix_push(void);
    void gs_matrix_rotaa(const struct axisang *rot);
    void gs_matrix_rotaa4f(float x, float y, float z, float angle);
    void gs_matrix_rotquat(const struct quat *rot);
    void gs_matrix_scale(const struct vec3 *scale);
    void gs_matrix_scale3f(float x, float y, float z);
    void gs_matrix_set(const struct matrix4 *matrix);
    void gs_matrix_translate(const struct vec3 *pos);
    void gs_matrix_translate3f(float x, float y, float z);
    void gs_matrix_transpose(void);
    void gs_normal3f(float x, float y, float z);
    void gs_normal3v(const struct vec3 *v);
    bool gs_nv12_available(void);
    bool gs_p010_available(void);
    size_t gs_param_get_num_annotations(const gs_eparam_t *param);
    void gs_perspective(float fovy, float aspect, float znear, float zfar);
    void gs_present(void);
    void gs_register_loss_callbacks(const struct gs_device_loss *callbacks);
    void gs_render_start(bool b_new);
    void gs_render_stop(enum gs_draw_mode mode);
    void gs_reset_blend_state(void);
    void gs_reset_viewport(void);
    void gs_resize(uint32_t x, uint32_t y);
    void gs_samplerstate_destroy(gs_samplerstate_t *samplerstate);
    void gs_set_2d_mode(void);
    void gs_set_3d_mode(double fovy, double znear, double zvar);
    void gs_set_cube_render_target(gs_texture_t *cubetex, int side, gs_zstencil_t *zstencil);
    void gs_set_cull_mode(enum gs_cull_mode mode);
    bool gs_set_linear_srgb(bool linear_srgb);
    void gs_set_render_target(gs_texture_t *tex, gs_zstencil_t *zstencil);
    void gs_set_render_target_with_color_space(gs_texture_t *tex, gs_zstencil_t *zstencil, enum gs_color_space space);
    void gs_set_scissor_rect(const struct gs_rect *rect);
    void gs_shader_destroy(gs_shader_t *shader);
    int gs_shader_get_num_params(const gs_shader_t *shader);
    void gs_shader_get_param_info(const gs_sparam_t *param, struct gs_shader_param_info *info);
    void gs_shader_set_bool(gs_sparam_t *param, bool val);
    void gs_shader_set_default(gs_sparam_t *param);
    void gs_shader_set_float(gs_sparam_t *param, float val);
    void gs_shader_set_int(gs_sparam_t *param, int val);
    void gs_shader_set_matrix3(gs_sparam_t *param, const struct matrix3 *val);
    void gs_shader_set_matrix4(gs_sparam_t *param, const struct matrix4 *val);
    void gs_shader_set_next_sampler(gs_sparam_t *param, gs_samplerstate_t *sampler);
    void gs_shader_set_texture(gs_sparam_t *param, gs_texture_t *val);
    void gs_shader_set_val(gs_sparam_t *param, const void *val, size_t size);
    void gs_shader_set_vec2(gs_sparam_t *param, const struct vec2 *val);
    void gs_shader_set_vec3(gs_sparam_t *param, const struct vec3 *val);
    void gs_shader_set_vec4(gs_sparam_t *param, const struct vec4 *val);
    bool gs_shared_texture_available(void);
    void gs_stage_texture(gs_stagesurf_t *dst, gs_texture_t *src);
    void gs_stagesurface_destroy(gs_stagesurf_t *stagesurf);
    enum gs_color_format gs_stagesurface_get_color_format(const gs_stagesurf_t *stagesurf);
    uint32_t gs_stagesurface_get_height(const gs_stagesurf_t *stagesurf);
    uint32_t gs_stagesurface_get_width(const gs_stagesurf_t *stagesurf);
    bool gs_stagesurface_map(gs_stagesurf_t *stagesurf, uint8_t **data, uint32_t *linesize);
    void gs_stagesurface_unmap(gs_stagesurf_t *stagesurf);
    void gs_stencil_function(enum gs_stencil_side side, enum gs_depth_test test);
    void gs_stencil_op(enum gs_stencil_side side, enum gs_stencil_op_type fail, enum gs_stencil_op_type zfail, enum gs_stencil_op_type zpass);
    void gs_swapchain_destroy(gs_swapchain_t *swapchain);
    size_t gs_technique_begin(gs_technique_t *technique);
    bool gs_technique_begin_pass(gs_technique_t *technique, size_t pass);
    bool gs_technique_begin_pass_by_name(gs_technique_t *technique, const char *name);
    void gs_technique_end(gs_technique_t *technique);
    void gs_technique_end_pass(gs_technique_t *technique);
    void gs_texcoord(float x, float y, int unit);
    void gs_texcoord2v(const struct vec2 *v, int unit);
    bool gs_texrender_begin(gs_texrender_t *texrender, uint32_t cx, uint32_t cy);
    bool gs_texrender_begin_with_color_space(gs_texrender_t *texrender, uint32_t cx, uint32_t cy, enum gs_color_space space);
    void gs_texrender_destroy(gs_texrender_t *texrender);
    void gs_texrender_end(gs_texrender_t *texrender);
    enum gs_color_format gs_texrender_get_format(const gs_texrender_t *texrender);
    void gs_texrender_reset(gs_texrender_t *texrender);
    int gs_texture_acquire_sync(gs_texture_t *tex, uint64_t key, uint32_t ms);
    bool gs_texture_create_nv12(gs_texture_t **tex_y, gs_texture_t **tex_uv, uint32_t width, uint32_t height, uint32_t flags);
    bool gs_texture_create_p010(gs_texture_t **tex_y, gs_texture_t **tex_uv, uint32_t width, uint32_t height, uint32_t flags);
    void gs_texture_destroy(gs_texture_t *tex);
    enum gs_color_format gs_texture_get_color_format(const gs_texture_t *tex);
    uint32_t gs_texture_get_height(const gs_texture_t *tex);
    uint32_t gs_texture_get_shared_handle(gs_texture_t *tex);
    uint32_t gs_texture_get_width(const gs_texture_t *tex);
    bool gs_texture_is_rect(const gs_texture_t *tex);
    bool gs_texture_map(gs_texture_t *tex, uint8_t **ptr, uint32_t *linesize);
    void gs_texture_release_dc(gs_texture_t *gdi_tex);
    int gs_texture_release_sync(gs_texture_t *tex, uint64_t key);
    void gs_texture_set_image(gs_texture_t *tex, const uint8_t *data, uint32_t linesize, bool invert);
    void gs_texture_unmap(gs_texture_t *tex);
    void gs_timer_begin(gs_timer_t *timer);
    void gs_timer_destroy(gs_timer_t *timer);
    void gs_timer_end(gs_timer_t *timer);
    bool gs_timer_get_data(gs_timer_t *timer, uint64_t *ticks);
    void gs_timer_range_begin(gs_timer_range_t *range);
    void gs_timer_range_destroy(gs_timer_range_t *timer);
    void gs_timer_range_end(gs_timer_range_t *range);
    bool gs_timer_range_get_data(gs_timer_range_t *range, bool *disjoint, uint64_t *frequency);
    void gs_unregister_loss_callbacks(void *data);
    void gs_update_color_space(void);
    void gs_vertex2f(float x, float y);
    void gs_vertex2v(const struct vec2 *v);
    void gs_vertex3f(float x, float y, float z);
    void gs_vertex3v(const struct vec3 *v);
    void gs_vertexbuffer_destroy(gs_vertbuffer_t *vertbuffer);
    void gs_vertexbuffer_flush(gs_vertbuffer_t *vertbuffer);
    void gs_vertexbuffer_flush_direct(gs_vertbuffer_t *vertbuffer, const struct gs_vb_data *data);
    void gs_viewport_pop(void);
    void gs_viewport_push(void);
    void gs_voltexture_destroy(gs_texture_t *voltex);
    enum gs_color_format gs_voltexture_get_color_format(const gs_texture_t *voltex);
    uint32_t gs_voltexture_get_depth(const gs_texture_t *voltex);
    uint32_t gs_voltexture_get_height(const gs_texture_t *voltex);
    uint32_t gs_voltexture_get_width(const gs_texture_t *voltex);
    void gs_zstencil_destroy(gs_zstencil_t *zstencil);
    void obs_add_core_module(const char *name);
    void obs_add_disabled_module(const char *name);
    void obs_add_main_rendered_callback(void (*rendered)(void *param), void *param);
    void obs_add_raw_video_callback2(const struct video_scale_info *conversion, uint32_t frame_rate_divisor, void (*callback)(void *param, struct video_data *frame), void *param);
    void obs_add_safe_module(const char *name);
    void obs_apply_private_data(obs_data_t *settings);
    bool obs_av1_keyframe(const uint8_t *data, size_t size);
    bool obs_avc_keyframe(const uint8_t *data, size_t size);
    void obs_canvas_enum_scenes(obs_canvas_t *canvas, bool (*enum_proc)(void *, obs_source_t *), void *param);
    uint32_t obs_canvas_get_flags(const obs_canvas_t *canvas);
    bool obs_canvas_get_video_info(const obs_canvas_t *canvas, struct obs_video_info *ovi);
    bool obs_canvas_has_video(obs_canvas_t *canvas);
    void obs_canvas_move_scene(obs_scene_t *scene, obs_canvas_t *dst);
    void obs_canvas_release(obs_canvas_t *canvas);
    void obs_canvas_remove(obs_canvas_t *canvas);
    bool obs_canvas_removed(obs_canvas_t *canvas);
    void obs_canvas_render(obs_canvas_t *canvas);
    bool obs_canvas_reset_video(obs_canvas_t *canvas, struct obs_video_info *ovi);
    void obs_canvas_scene_remove(obs_scene_t *scene);
    void obs_canvas_set_channel(obs_canvas_t *canvas, uint32_t channel, obs_source_t *source);
    void obs_canvas_set_name(obs_canvas_t *canvas, const char *name);
    bool obs_create_disabled_module(obs_module_t **module, const char *path, const char *data_path, enum obs_module_load_state state);
    void obs_data_array_enum(obs_data_array_t *array, void (*cb)(obs_data_t *data, void *param), void *param);
    void obs_data_array_push_back_array(obs_data_array_t *array, obs_data_array_t *array2);
    bool obs_data_get_autoselect_bool(obs_data_t *data, const char *name);
    double obs_data_get_autoselect_double(obs_data_t *data, const char *name);
    bool obs_data_get_autoselect_frames_per_second(obs_data_t *data, const char *name, struct media_frames_per_second *fps, const char **option);
    long long obs_data_get_autoselect_int(obs_data_t *data, const char *name);
    void obs_data_get_autoselect_quat(obs_data_t *data, const char *name, struct quat *val);
    void obs_data_get_autoselect_vec2(obs_data_t *data, const char *name, struct vec2 *val);
    void obs_data_get_autoselect_vec3(obs_data_t *data, const char *name, struct vec3 *val);
    void obs_data_get_autoselect_vec4(obs_data_t *data, const char *name, struct vec4 *val);
    bool obs_data_get_default_frames_per_second(obs_data_t *data, const char *name, struct media_frames_per_second *fps, const char **option);
    void obs_data_get_default_quat(obs_data_t *data, const char *name, struct quat *val);
    void obs_data_get_default_vec2(obs_data_t *data, const char *name, struct vec2 *val);
    void obs_data_get_default_vec3(obs_data_t *data, const char *name, struct vec3 *val);
    void obs_data_get_default_vec4(obs_data_t *data, const char *name, struct vec4 *val);
    bool obs_data_get_frames_per_second(obs_data_t *data, const char *name, struct media_frames_per_second *fps, const char **option);
    void obs_data_get_quat(obs_data_t *data, const char *name, struct quat *val);
    void obs_data_get_vec2(obs_data_t *data, const char *name, struct vec2 *val);
    void obs_data_get_vec3(obs_data_t *data, const char *name, struct vec3 *val);
    void obs_data_get_vec4(obs_data_t *data, const char *name, struct vec4 *val);
    bool obs_data_has_autoselect_value(obs_data_t *data, const char *name);
    bool obs_data_item_get_autoselect_bool(obs_data_item_t *item);
    double obs_data_item_get_autoselect_double(obs_data_item_t *item);
    bool obs_data_item_get_autoselect_frames_per_second(obs_data_item_t *item, struct media_frames_per_second *fps, const char **option);
    long long obs_data_item_get_autoselect_int(obs_data_item_t *item);
    bool obs_data_item_get_bool(obs_data_item_t *item);
    bool obs_data_item_get_default_bool(obs_data_item_t *item);
    double obs_data_item_get_default_double(obs_data_item_t *item);
    bool obs_data_item_get_default_frames_per_second(obs_data_item_t *item, struct media_frames_per_second *fps, const char **option);
    long long obs_data_item_get_default_int(obs_data_item_t *item);
    double obs_data_item_get_double(obs_data_item_t *item);
    bool obs_data_item_get_frames_per_second(obs_data_item_t *item, struct media_frames_per_second *fps, const char **option);
    long long obs_data_item_get_int(obs_data_item_t *item);
    bool obs_data_item_has_autoselect_value(obs_data_item_t *data);
    bool obs_data_item_has_default_value(obs_data_item_t *data);
    bool obs_data_item_has_user_value(obs_data_item_t *data);
    enum obs_data_number_type obs_data_item_numtype(obs_data_item_t *item);
    void obs_data_item_remove(obs_data_item_t **item);
    void obs_data_item_set_array(obs_data_item_t **item, obs_data_array_t *val);
    void obs_data_item_set_autoselect_array(obs_data_item_t **item, obs_data_array_t *val);
    void obs_data_item_set_autoselect_bool(obs_data_item_t **item, bool val);
    void obs_data_item_set_autoselect_double(obs_data_item_t **item, double val);
    void obs_data_item_set_autoselect_frames_per_second(obs_data_item_t **item, struct media_frames_per_second fps, const char *option);
    void obs_data_item_set_autoselect_int(obs_data_item_t **item, long long val);
    void obs_data_item_set_autoselect_obj(obs_data_item_t **item, obs_data_t *val);
    void obs_data_item_set_autoselect_string(obs_data_item_t **item, const char *val);
    void obs_data_item_set_bool(obs_data_item_t **item, bool val);
    void obs_data_item_set_default_array(obs_data_item_t **item, obs_data_array_t *val);
    void obs_data_item_set_default_bool(obs_data_item_t **item, bool val);
    void obs_data_item_set_default_double(obs_data_item_t **item, double val);
    void obs_data_item_set_default_frames_per_second(obs_data_item_t **item, struct media_frames_per_second fps, const char *option);
    void obs_data_item_set_default_int(obs_data_item_t **item, long long val);
    void obs_data_item_set_default_obj(obs_data_item_t **item, obs_data_t *val);
    void obs_data_item_set_default_string(obs_data_item_t **item, const char *val);
    void obs_data_item_set_double(obs_data_item_t **item, double val);
    void obs_data_item_set_frames_per_second(obs_data_item_t **item, struct media_frames_per_second fps, const char *option);
    void obs_data_item_set_int(obs_data_item_t **item, long long val);
    void obs_data_item_set_obj(obs_data_item_t **item, obs_data_t *val);
    void obs_data_item_set_string(obs_data_item_t **item, const char *val);
    void obs_data_item_unset_autoselect_value(obs_data_item_t *data);
    void obs_data_item_unset_default_value(obs_data_item_t *data);
    void obs_data_item_unset_user_value(obs_data_item_t *data);
    bool obs_data_save_json_pretty_safe(obs_data_t *data, const char *file, const char *temp_ext, const char *backup_ext);
    void obs_data_set_autoselect_array(obs_data_t *data, const char *name, obs_data_array_t *arr);
    void obs_data_set_autoselect_bool(obs_data_t *data, const char *name, bool val);
    void obs_data_set_autoselect_double(obs_data_t *data, const char *name, double val);
    void obs_data_set_autoselect_frames_per_second(obs_data_t *data, const char *name, struct media_frames_per_second fps, const char *option);
    void obs_data_set_autoselect_int(obs_data_t *data, const char *name, long long val);
    void obs_data_set_autoselect_obj(obs_data_t *data, const char *name, obs_data_t *obj);
    void obs_data_set_autoselect_quat(obs_data_t *data, const char *name, const struct quat *val);
    void obs_data_set_autoselect_string(obs_data_t *data, const char *name, const char *val);
    void obs_data_set_autoselect_vec2(obs_data_t *data, const char *name, const struct vec2 *val);
    void obs_data_set_autoselect_vec3(obs_data_t *data, const char *name, const struct vec3 *val);
    void obs_data_set_autoselect_vec4(obs_data_t *data, const char *name, const struct vec4 *val);
    void obs_data_set_default_array(obs_data_t *data, const char *name, obs_data_array_t *arr);
    void obs_data_set_default_frames_per_second(obs_data_t *data, const char *name, struct media_frames_per_second fps, const char *option);
    void obs_data_set_default_quat(obs_data_t *data, const char *name, const struct quat *val);
    void obs_data_set_default_vec2(obs_data_t *data, const char *name, const struct vec2 *val);
    void obs_data_set_default_vec3(obs_data_t *data, const char *name, const struct vec3 *val);
    void obs_data_set_default_vec4(obs_data_t *data, const char *name, const struct vec4 *val);
    void obs_data_set_frames_per_second(obs_data_t *data, const char *name, struct media_frames_per_second fps, const char *option);
    void obs_data_set_quat(obs_data_t *data, const char *name, const struct quat *val);
    void obs_data_set_vec2(obs_data_t *data, const char *name, const struct vec2 *val);
    void obs_data_set_vec3(obs_data_t *data, const char *name, const struct vec3 *val);
    void obs_data_set_vec4(obs_data_t *data, const char *name, const struct vec4 *val);
    void obs_data_unset_autoselect_value(obs_data_t *data, const char *name);
    float obs_db_to_mul(float db);
    void obs_display_update_color_space(obs_display_t *display);
    uint32_t obs_encoder_get_caps(const obs_encoder_t *encoder);
    uint32_t obs_encoder_get_encoded_frames(const obs_encoder_t *encoder);
    bool obs_encoder_get_extra_data(const obs_encoder_t *encoder, uint8_t **extra_data, size_t *size);
    uint32_t obs_encoder_get_frame_rate_divisor(const obs_encoder_t *encoder);
    size_t obs_encoder_get_frame_size(const obs_encoder_t *encoder);
    uint32_t obs_encoder_get_height(const obs_encoder_t *encoder);
    size_t obs_encoder_get_mixer_index(const obs_encoder_t *encoder);
    uint64_t obs_encoder_get_pause_offset(const obs_encoder_t *encoder);
    enum video_colorspace obs_encoder_get_preferred_color_space(const obs_encoder_t *encoder);
    enum video_range_type obs_encoder_get_preferred_range(const obs_encoder_t *encoder);
    enum video_format obs_encoder_get_preferred_video_format(const obs_encoder_t *encoder);
    uint32_t obs_encoder_get_priming_samples(const obs_encoder_t *encoder);
    uint32_t obs_encoder_get_sample_rate(const obs_encoder_t *encoder);
    enum obs_scale_type obs_encoder_get_scale_type(obs_encoder_t *encoder);
    uint32_t obs_encoder_get_width(const obs_encoder_t *encoder);
    bool obs_encoder_gpu_scaling_enabled(obs_encoder_t *encoder);
    void obs_encoder_group_destroy(obs_encoder_group_t *group);
    enum obs_module_load_state obs_encoder_load_state(const char *id);
    void obs_encoder_packet_ref(struct encoder_packet *dst, struct encoder_packet *src);
    void obs_encoder_packet_release(struct encoder_packet *packet);
    bool obs_encoder_paused(const obs_encoder_t *output);
    bool obs_encoder_scaling_enabled(const obs_encoder_t *encoder);
    bool obs_encoder_set_frame_rate_divisor(obs_encoder_t *encoder, uint32_t divisor);
    void obs_encoder_set_gpu_scale_type(obs_encoder_t *encoder, enum obs_scale_type gpu_scale_type);
    bool obs_encoder_set_group(obs_encoder_t *encoder, obs_encoder_group_t *group);
    void obs_encoder_set_last_error(obs_encoder_t *encoder, const char *message);
    void obs_encoder_set_preferred_color_space(obs_encoder_t *encoder, enum video_colorspace colorspace);
    void obs_encoder_set_preferred_range(obs_encoder_t *encoder, enum video_range_type range);
    void obs_encoder_set_preferred_video_format(obs_encoder_t *encoder, enum video_format format);
    void obs_encoder_set_scaled_size(obs_encoder_t *encoder, uint32_t width, uint32_t height);
    bool obs_encoder_video_tex_active(const obs_encoder_t *encoder, enum video_format format);
    void obs_enter_graphics(void);
    void obs_enum_canvases(bool (*enum_proc)(void *, obs_canvas_t *), void *param);
    void obs_enum_encoders(bool (*enum_proc)(void *, obs_encoder_t *), void *param);
    void obs_enum_hotkey_bindings(obs_hotkey_binding_enum_func func, void *data);
    void obs_enum_modules(obs_enum_module_callback_t callback, void *param);
    bool obs_enum_output_protocols(size_t idx, char **protocol);
    void obs_enum_output_types_with_protocol(const char *protocol, void *data, bool (*enum_cb)(void *data, const char *id));
    void obs_enum_outputs(bool (*enum_proc)(void *, obs_output_t *), void *param);
    void obs_enum_services(bool (*enum_proc)(void *, obs_service_t *), void *param);
    void obs_extract_av1_headers(const uint8_t *packet, size_t size, uint8_t **new_packet_data, size_t *new_packet_size, uint8_t **header_data, size_t *header_size);
    void obs_extract_avc_headers(const uint8_t *packet, size_t size, uint8_t **new_packet_data, size_t *new_packet_size, uint8_t **header_data, size_t *header_size, uint8_t **sei_data, size_t *sei_size);
    void obs_extract_hevc_headers(const uint8_t *packet, size_t size, uint8_t **new_packet_data, size_t *new_packet_size, uint8_t **header_data, size_t *header_size, uint8_t **sei_data, size_t *sei_size);
    void obs_find_modules(obs_find_module_callback_t callback, void *param);
    void obs_find_modules2(obs_find_module_callback2_t callback, void *param);
    double obs_get_active_fps(void);
    bool obs_get_audio_info2(struct obs_audio_info2 *oai2);
    uint64_t obs_get_average_frame_time_ns(void);
    struct obs_cmdline_args obs_get_cmdline_args(void);
    uint32_t obs_get_encoder_caps(const char *encoder_id);
    enum obs_encoder_type obs_get_encoder_type(const char *id);
    uint64_t obs_get_frame_interval_ns(void);
    uint32_t obs_get_lagged_frames(void);
    bool obs_get_module_allow_disable(const char *name);
    uint32_t obs_get_output_flags(const char *id);
    uint32_t obs_get_source_output_flags(const char *id);
    uint32_t obs_get_total_frames(void);
    bool obs_hevc_keyframe(const uint8_t *data, size_t size);
    obs_hotkey_id obs_hotkey_binding_get_hotkey_id(obs_hotkey_binding_t *binding);
    obs_key_combination_t obs_hotkey_binding_get_key_combination(obs_hotkey_binding_t *binding);
    obs_hotkey_id obs_hotkey_get_pair_partner_id(const obs_hotkey_t *key);
    obs_hotkey_registerer_t obs_hotkey_get_registerer_type(const obs_hotkey_t *key);
    void obs_hotkey_load_bindings(obs_hotkey_id id, obs_key_combination_t *combinations, size_t num);
    void obs_hotkey_pair_load(obs_hotkey_pair_id id, obs_data_array_t *data0, obs_data_array_t *data1);
    obs_hotkey_pair_id obs_hotkey_pair_register_encoder(obs_encoder_t *encoder, const char *name0, const char *description0, const char *name1, const char *description1, obs_hotkey_active_func func0, obs_hotkey_active_func func1, void *data0, void *data1);
    obs_hotkey_pair_id obs_hotkey_pair_register_frontend(const char *name0, const char *description0, const char *name1, const char *description1, obs_hotkey_active_func func0, obs_hotkey_active_func func1, void *data0, void *data1);
    obs_hotkey_pair_id obs_hotkey_pair_register_output(obs_output_t *output, const char *name0, const char *description0, const char *name1, const char *description1, obs_hotkey_active_func func0, obs_hotkey_active_func func1, void *data0, void *data1);
    obs_hotkey_pair_id obs_hotkey_pair_register_service(obs_service_t *service, const char *name0, const char *description0, const char *name1, const char *description1, obs_hotkey_active_func func0, obs_hotkey_active_func func1, void *data0, void *data1);
    obs_hotkey_pair_id obs_hotkey_pair_register_source(obs_source_t *source, const char *name0, const char *description0, const char *name1, const char *description1, obs_hotkey_active_func func0, obs_hotkey_active_func func1, void *data0, void *data1);
    void obs_hotkey_pair_save(obs_hotkey_pair_id id, obs_data_array_t **p_data0, obs_data_array_t **p_data1);
    void obs_hotkey_pair_set_descriptions(obs_hotkey_pair_id id, const char *desc0, const char *desc1);
    void obs_hotkey_pair_set_names(obs_hotkey_pair_id id, const char *name0, const char *name1);
    void obs_hotkey_pair_unregister(obs_hotkey_pair_id id);
    obs_hotkey_id obs_hotkey_register_encoder(obs_encoder_t *encoder, const char *name, const char *description, obs_hotkey_func func, void *data);
    obs_hotkey_id obs_hotkey_register_output(obs_output_t *output, const char *name, const char *description, obs_hotkey_func func, void *data);
    obs_hotkey_id obs_hotkey_register_service(obs_service_t *service, const char *name, const char *description, obs_hotkey_func func, void *data);
    void obs_hotkey_set_callback_routing_func(obs_hotkey_callback_router_func func, void *data);
    void obs_hotkey_set_description(obs_hotkey_id id, const char *desc);
    void obs_hotkey_set_name(obs_hotkey_id id, const char *name);
    void obs_hotkey_update_atomic(obs_hotkey_atomic_update_func func, void *data);
    void obs_hotkeys_load_encoder(obs_encoder_t *encoder, obs_data_t *hotkeys);
    void obs_hotkeys_load_output(obs_output_t *output, obs_data_t *hotkeys);
    void obs_hotkeys_load_service(obs_service_t *service, obs_data_t *hotkeys);
    void obs_hotkeys_load_source(obs_source_t *source, obs_data_t *hotkeys);
    void obs_hotkeys_set_audio_hotkeys_translations(const char *mute, const char *unmute, const char *push_to_mute, const char *push_to_talk);
    void obs_hotkeys_set_sceneitem_hotkeys_translations(const char *show, const char *hide);
    void obs_hotkeys_set_translations_s(struct obs_hotkeys_translations *translations, size_t size);
    bool obs_in_task_thread(enum obs_task_type type);
    bool obs_init_module(obs_module_t *module);
    void obs_init_win32_crash_handler(void);
    bool obs_is_output_protocol_registered(const char *protocol);
    bool obs_is_source_configurable(const char *id);
    void obs_key_combination_to_str(obs_key_combination_t key, struct dstr *str);
    obs_key_t obs_key_from_virtual_key(int code);
    void obs_key_to_str(obs_key_t key, struct dstr *str);
    int obs_key_to_virtual_key(obs_key_t key);
    void obs_leave_graphics(void);
    void obs_load_all_modules2(struct obs_module_failure_info *mfi);
    void obs_log_loaded_modules(void);
    void obs_missing_file_destroy(obs_missing_file_t *file);
    void obs_missing_file_issue_callback(obs_missing_file_t *file, const char *new_path);
    void obs_missing_file_release(obs_missing_file_t *file);
    void obs_missing_files_add_file(obs_missing_files_t *files, obs_missing_file_t *file);
    void obs_missing_files_append(obs_missing_files_t *dst, obs_missing_files_t *src);
    size_t obs_missing_files_count(obs_missing_files_t *files);
    void obs_missing_files_destroy(obs_missing_files_t *files);
    void obs_module_add_encoder(obs_module_t *module, const char *id);
    void obs_module_add_output(obs_module_t *module, const char *id);
    void obs_module_add_service(obs_module_t *module, const char *id);
    void obs_module_add_source(obs_module_t *module, const char *id);
    void obs_module_failure_info_free(struct obs_module_failure_info *mfi);
    bool obs_module_get_locale_string(const obs_module_t *mod, const char *lookup_string, const char **translated_string);
    float obs_mul_to_db(float mul);
    bool obs_nv12_tex_active(void);
    enum obs_obj_type obs_obj_get_type(void *obj);
    bool obs_obj_invalid(void *obj);
    bool obs_obj_is_private(void *obj);
    void obs_object_release(obs_object_t *object);
    int obs_open_module(obs_module_t **module, const char *path, const char *data_path);
    bool obs_output_begin_data_capture(obs_output_t *output, uint32_t flags);
    bool obs_output_can_begin_data_capture(const obs_output_t *output, uint32_t flags);
    void obs_output_caption(obs_output_t *output, const struct obs_source_cea_708 *captions);
    void obs_output_end_data_capture(obs_output_t *output);
    uint32_t obs_output_get_height(const obs_output_t *output);
    uint32_t obs_output_get_height2(const obs_output_t *output, size_t idx);
    uint64_t obs_output_get_pause_offset(obs_output_t *output);
    uint32_t obs_output_get_width(const obs_output_t *output);
    uint32_t obs_output_get_width2(const obs_output_t *output, size_t idx);
    bool obs_output_initialize_encoders(obs_output_t *output, uint32_t flags);
    enum obs_module_load_state obs_output_load_state(const char *id);
    void obs_output_output_caption_text1(obs_output_t *output, const char *text);
    void obs_output_output_caption_text2(obs_output_t *output, const char *text, double display_duration);
    void obs_output_set_audio_conversion(obs_output_t *output, const struct audio_convert_info *conversion);
    void obs_output_set_last_error(obs_output_t *output, const char *message);
    void obs_output_set_media(obs_output_t *output, video_t *video, audio_t *audio);
    void obs_output_set_preferred_size(obs_output_t *output, uint32_t width, uint32_t height);
    void obs_output_set_preferred_size2(obs_output_t *output, uint32_t width, uint32_t height, size_t idx);
    void obs_output_set_reconnect_callback(obs_output_t *output, bool (*reconnect_cb)(void *data, obs_output_t *output, int code), void *param);
    void obs_output_set_video_conversion(obs_output_t *output, const struct video_scale_info *conversion);
    void obs_output_set_video_encoder2(obs_output_t *output, obs_encoder_t *encoder, size_t idx);
    void obs_output_signal_stop(obs_output_t *output, int code);
    bool obs_p010_tex_active(void);
    size_t obs_parse_avc_header(uint8_t **header, const uint8_t *data, size_t size);
    void obs_parse_avc_packet(struct encoder_packet *avc_packet, const struct encoder_packet *src);
    int obs_parse_avc_packet_priority(const struct encoder_packet *packet);
    void obs_parse_hevc_packet(struct encoder_packet *hevc_packet, const struct encoder_packet *src);
    int obs_parse_hevc_packet_priority(const struct encoder_packet *packet);
    void obs_properties_apply_settings(obs_properties_t *props, obs_data_t *settings);
    uint32_t obs_properties_get_flags(obs_properties_t *props);
    void obs_properties_remove_by_name(obs_properties_t *props, const char *property);
    void obs_properties_set_flags(obs_properties_t *props, uint32_t flags);
    void obs_properties_set_param(obs_properties_t *props, void *param, void (*destroy)(void *param));
    bool obs_property_button_clicked(obs_property_t *p, void *obj);
    void obs_property_button_set_type(obs_property_t *p, enum obs_button_type type);
    void obs_property_button_set_url(obs_property_t *p, char *url);
    enum obs_button_type obs_property_button_type(obs_property_t *p);
    enum obs_editable_list_type obs_property_editable_list_type(obs_property_t *p);
    void obs_property_float_set_limits(obs_property_t *p, double min, double max, double step);
    void obs_property_float_set_suffix(obs_property_t *p, const char *suffix);
    void obs_property_frame_rate_clear(obs_property_t *p);
    size_t obs_property_frame_rate_fps_range_add(obs_property_t *p, struct media_frames_per_second min, struct media_frames_per_second max);
    void obs_property_frame_rate_fps_range_insert(obs_property_t *p, size_t idx, struct media_frames_per_second min, struct media_frames_per_second max);
    struct media_frames_per_second obs_property_frame_rate_fps_range_max(obs_property_t *p, size_t idx);
    struct media_frames_per_second obs_property_frame_rate_fps_range_min(obs_property_t *p, size_t idx);
    void obs_property_frame_rate_fps_ranges_clear(obs_property_t *p);
    size_t obs_property_frame_rate_fps_ranges_count(obs_property_t *p);
    size_t obs_property_frame_rate_option_add(obs_property_t *p, const char *name, const char *description);
    void obs_property_frame_rate_option_insert(obs_property_t *p, size_t idx, const char *name, const char *description);
    void obs_property_frame_rate_options_clear(obs_property_t *p);
    size_t obs_property_frame_rate_options_count(obs_property_t *p);
    enum obs_group_type obs_property_group_type(obs_property_t *p);
    void obs_property_int_set_limits(obs_property_t *p, int min, int max, int step);
    void obs_property_int_set_suffix(obs_property_t *p, const char *suffix);
    size_t obs_property_list_add_bool(obs_property_t *p, const char *name, bool val);
    size_t obs_property_list_add_float(obs_property_t *p, const char *name, double val);
    size_t obs_property_list_add_int(obs_property_t *p, const char *name, long long val);
    size_t obs_property_list_add_string(obs_property_t *p, const char *name, const char *val);
    void obs_property_list_clear(obs_property_t *p);
    void obs_property_list_insert_bool(obs_property_t *p, size_t idx, const char *name, bool val);
    void obs_property_list_insert_float(obs_property_t *p, size_t idx, const char *name, double val);
    void obs_property_list_insert_int(obs_property_t *p, size_t idx, const char *name, long long val);
    void obs_property_list_insert_string(obs_property_t *p, size_t idx, const char *name, const char *val);
    bool obs_property_list_item_bool(obs_property_t *p, size_t idx);
    void obs_property_list_item_disable(obs_property_t *p, size_t idx, bool disabled);
    void obs_property_list_item_remove(obs_property_t *p, size_t idx);
    void obs_property_set_description(obs_property_t *p, const char *description);
    void obs_property_set_enabled(obs_property_t *p, bool enabled);
    void obs_property_set_long_description(obs_property_t *p, const char *long_description);
    void obs_property_set_modified_callback(obs_property_t *p, obs_property_modified_t modified);
    void obs_property_set_modified_callback2(obs_property_t *p, obs_property_modified2_t modified, void *priv);
    void obs_property_set_visible(obs_property_t *p, bool visible);
    void obs_property_text_set_info_type(obs_property_t *p, enum obs_text_info_type type);
    void obs_property_text_set_info_word_wrap(obs_property_t *p, bool word_wrap);
    void obs_property_text_set_monospace(obs_property_t *p, bool monospace);
    void obs_queue_task(enum obs_task_type type, obs_task_t task, void *param, bool wait);
    void obs_register_encoder_s(const struct obs_encoder_info *info, size_t size);
    void obs_register_output_s(const struct obs_output_info *info, size_t size);
    void obs_register_service_s(const struct obs_service_info *info, size_t size);
    void obs_register_source_s(const struct obs_source_info *info, size_t size);
    void obs_remove_main_rendered_callback(void (*rendered)(void *param), void *param);
    void obs_render_canvas_texture(obs_canvas_t *canvas);
    void obs_render_canvas_texture_src_color_only(obs_canvas_t *canvas);
    void obs_render_main_texture_src_color_only(void);
    bool obs_reset_audio2(const struct obs_audio_info2 *oai);
    void obs_reset_source_uuids(void);
    void obs_scene_atomic_update(obs_scene_t *scene, obs_scene_atomic_update_func func, void *data);
    bool obs_scene_is_group(const obs_scene_t *scene);
    void obs_scene_load_transform_states(const char *state);
    void obs_scene_prune_sources(obs_scene_t *scene);
    bool obs_scene_reorder_items(obs_scene_t *scene, obs_sceneitem_t *const *item_order, size_t item_order_size);
    bool obs_scene_reorder_items2(obs_scene_t *scene, struct obs_sceneitem_order_info *item_order, size_t item_order_size);
    void obs_sceneitem_defer_group_resize_begin(obs_sceneitem_t *item);
    void obs_sceneitem_defer_group_resize_end(obs_sceneitem_t *item);
    void obs_sceneitem_do_transition(obs_sceneitem_t *item, bool visible);
    void obs_sceneitem_get_box_scale(const obs_sceneitem_t *item, struct vec2 *scale);
    void obs_sceneitem_get_box_transform(const obs_sceneitem_t *item, struct matrix4 *transform);
    void obs_sceneitem_get_draw_transform(const obs_sceneitem_t *item, struct matrix4 *transform);
    int64_t obs_sceneitem_get_id(const obs_sceneitem_t *item);
    enum obs_scale_type obs_sceneitem_get_scale_filter(obs_sceneitem_t *item);
    uint32_t obs_sceneitem_get_transition_duration(obs_sceneitem_t *item, bool show);
    void obs_sceneitem_group_enum_items(obs_sceneitem_t *group, bool (*callback)(obs_scene_t *, obs_sceneitem_t *, void *), void *param);
    void obs_sceneitem_group_ungroup(obs_sceneitem_t *group);
    void obs_sceneitem_group_ungroup2(obs_sceneitem_t *group, bool signal);
    void obs_sceneitem_save(obs_sceneitem_t *item, obs_data_array_t *arr);
    void obs_sceneitem_select(obs_sceneitem_t *item, bool select);
    bool obs_sceneitem_selected(const obs_sceneitem_t *item);
    void obs_sceneitem_set_id(obs_sceneitem_t *sceneitem, int64_t id);
    void obs_sceneitem_set_order(obs_sceneitem_t *item, enum obs_order_movement movement);
    void obs_sceneitem_set_scale_filter(obs_sceneitem_t *item, enum obs_scale_type filter);
    void obs_sceneitem_set_transition(obs_sceneitem_t *item, bool show, obs_source_t *transition);
    void obs_sceneitem_set_transition_duration(obs_sceneitem_t *item, bool show, uint32_t duration_ms);
    void obs_sceneitem_transition_load(struct obs_scene_item *item, obs_data_t *data, bool show);
    void obs_sceneitems_add(obs_scene_t *scene, obs_data_array_t *data);
    void obs_service_apply_encoder_settings(obs_service_t *service, obs_data_t *video_encoder_settings, obs_data_t *audio_encoder_settings);
    bool obs_service_can_try_to_connect(const obs_service_t *service);
    void obs_service_get_max_bitrate(const obs_service_t *service, int *video_bitrate, int *audio_bitrate);
    void obs_service_get_max_fps(const obs_service_t *service, int *fps);
    void obs_service_get_supported_resolutions(const obs_service_t *service, struct obs_service_resolution **resolutions, size_t *count);
    enum obs_module_load_state obs_service_load_state(const char *id);
    void obs_set_cmdline_args(int argc, const char *const *argv);
    void obs_set_private_data(obs_data_t *settings);
    void obs_set_ui_task_handler(obs_task_handler_t handler);
    bool obs_source_add_active_child(obs_source_t *parent, obs_source_t *child);
    void obs_source_add_audio_pause_callback(obs_source_t *source, signal_callback_t callback, void *param);
    void obs_source_add_caption_callback(obs_source_t *source, obs_source_caption_t callback, void *param);
    bool obs_source_async_decoupled(const obs_source_t *source);
    bool obs_source_async_unbuffered(const obs_source_t *source);
    void obs_source_audio_output_capture_device_changed(obs_source_t *source, const char *device_id);
    bool obs_source_audio_pending(const obs_source_t *source);
    bool obs_source_configurable(const obs_source_t *source);
    void obs_source_default_render(obs_source_t *source);
    void obs_source_draw(gs_texture_t *image, int x, int y, uint32_t cx, uint32_t cy, bool flip);
    void obs_source_draw_set_color_matrix(const struct matrix4 *color_matrix, const struct vec3 *color_range_min, const struct vec3 *color_range_max);
    void obs_source_enable_push_to_mute(obs_source_t *source, bool enabled);
    void obs_source_enable_push_to_talk(obs_source_t *source, bool enabled);
    void obs_source_filter_set_order(obs_source_t *source, obs_source_t *filter, enum obs_order_movement movement);
    void obs_source_frame_copy(struct obs_source_frame *dst, const struct obs_source_frame *src);
    void obs_source_frame_init(struct obs_source_frame *frame, enum video_format format, uint32_t width, uint32_t height);
    void obs_source_get_audio_mix(const obs_source_t *source, struct obs_source_audio_mix *audio);
    uint64_t obs_source_get_audio_timestamp(const obs_source_t *source);
    uint32_t obs_source_get_base_height(obs_source_t *source);
    uint32_t obs_source_get_base_width(obs_source_t *source);
    enum gs_color_space obs_source_get_color_space(obs_source_t *source, size_t count, const enum gs_color_space *preferred_spaces);
    uint32_t obs_source_get_flags(const obs_source_t *source);
    uint32_t obs_source_get_last_obs_version(const obs_source_t *source);
    uint64_t obs_source_get_push_to_mute_delay(obs_source_t *source);
    uint64_t obs_source_get_push_to_talk_delay(obs_source_t *source);
    bool obs_source_get_texcoords_centered(obs_source_t *source);
    enum obs_source_type obs_source_get_type(const obs_source_t *source);
    bool obs_source_is_group(const obs_source_t *source);
    bool obs_source_is_hidden(obs_source_t *source);
    bool obs_source_is_scene(const obs_source_t *source);
    void obs_source_load(obs_source_t *source);
    void obs_source_load2(obs_source_t *source);
    enum obs_module_load_state obs_source_load_state(const char *id);
    void obs_source_media_ended(obs_source_t *source);
    void obs_source_media_started(obs_source_t *source);
    void obs_source_output_audio(obs_source_t *source, const struct obs_source_audio *audio);
    void obs_source_output_cea708(obs_source_t *source, const struct obs_source_cea_708 *captions);
    void obs_source_output_video(obs_source_t *source, const struct obs_source_frame *frame);
    void obs_source_output_video2(obs_source_t *source, const struct obs_source_frame2 *frame);
    void obs_source_preload_video(obs_source_t *source, const struct obs_source_frame *frame);
    void obs_source_preload_video2(obs_source_t *source, const struct obs_source_frame2 *frame);
    bool obs_source_process_filter_begin(obs_source_t *filter, enum gs_color_format format, enum obs_allow_direct_render allow_direct);
    bool obs_source_process_filter_begin_with_color_space(obs_source_t *filter, enum gs_color_format format, enum gs_color_space space, enum obs_allow_direct_render allow_direct);
    void obs_source_process_filter_end(obs_source_t *filter, gs_effect_t *effect, uint32_t width, uint32_t height);
    void obs_source_process_filter_tech_end(obs_source_t *filter, gs_effect_t *effect, uint32_t width, uint32_t height, const char *tech_name);
    bool obs_source_push_to_mute_enabled(obs_source_t *source);
    bool obs_source_push_to_talk_enabled(obs_source_t *source);
    void obs_source_release_frame(obs_source_t *source, struct obs_source_frame *frame);
    void obs_source_remove_active_child(obs_source_t *parent, obs_source_t *child);
    void obs_source_remove_audio_pause_callback(obs_source_t *source, signal_callback_t callback, void *param);
    void obs_source_remove_caption_callback(obs_source_t *source, obs_source_caption_t callback, void *param);
    void obs_source_replace_missing_file(obs_missing_file_cb cb, obs_source_t *source, const char *new_path, void *data);
    void obs_source_reset_settings(obs_source_t *source, obs_data_t *settings);
    void obs_source_save(obs_source_t *source);
    void obs_source_send_focus(obs_source_t *source, bool focus);
    void obs_source_send_key_click(obs_source_t *source, const struct obs_key_event *event, bool key_up);
    void obs_source_send_mouse_click(obs_source_t *source, const struct obs_mouse_event *event, int32_t type, bool mouse_up, uint32_t click_count);
    void obs_source_send_mouse_move(obs_source_t *source, const struct obs_mouse_event *event, bool mouse_leave);
    void obs_source_send_mouse_wheel(obs_source_t *source, const struct obs_mouse_event *event, int x_delta, int y_delta);
    void obs_source_set_async_decoupled(obs_source_t *source, bool decouple);
    void obs_source_set_async_rotation(obs_source_t *source, long rotation);
    void obs_source_set_async_unbuffered(obs_source_t *source, bool unbuffered);
    void obs_source_set_default_flags(obs_source_t *source, uint32_t flags);
    void obs_source_set_flags(obs_source_t *source, uint32_t flags);
    void obs_source_set_hidden(obs_source_t *source, bool hidden);
    void obs_source_set_push_to_mute_delay(obs_source_t *source, uint64_t delay);
    void obs_source_set_push_to_talk_delay(obs_source_t *source, uint64_t delay);
    void obs_source_set_video_frame(obs_source_t *source, const struct obs_source_frame *frame);
    void obs_source_set_video_frame2(obs_source_t *source, const struct obs_source_frame2 *frame);
    void obs_source_show_preloaded_video(obs_source_t *source);
    void obs_source_skip_video_filter(obs_source_t *filter);
    bool obs_source_type_is_group(const char *id);
    bool obs_source_type_is_scene(const char *id);
    void obs_source_update_properties(obs_source_t *source);
    bool obs_transition_audio_render(obs_source_t *transition, uint64_t *ts_out, struct obs_source_audio_mix *audio, uint32_t mixers, size_t channels, size_t sample_rate, obs_transition_audio_mix_callback_t mix_a_callback, obs_transition_audio_mix_callback_t mix_b_callback);
    void obs_transition_enable_fixed(obs_source_t *transition, bool enable, uint32_t duration_ms);
    bool obs_transition_fixed(obs_source_t *transition);
    void obs_transition_force_stop(obs_source_t *transition);
    uint32_t obs_transition_get_alignment(const obs_source_t *transition);
    enum obs_transition_scale_type obs_transition_get_scale_type(const obs_source_t *transition);
    bool obs_transition_is_active(obs_source_t *transition);
    void obs_transition_set_alignment(obs_source_t *transition, uint32_t alignment);
    void obs_transition_set_manual_time(obs_source_t *transition, float t);
    void obs_transition_set_manual_torque(obs_source_t *transition, float torque, float clamp);
    void obs_transition_set_scale_type(obs_source_t *transition, enum obs_transition_scale_type type);
    void obs_transition_swap_begin(obs_source_t *tr_dest, obs_source_t *tr_source);
    void obs_transition_swap_end(obs_source_t *tr_dest, obs_source_t *tr_source);
    enum gs_color_space obs_transition_video_get_color_space(obs_source_t *transition);
    void obs_transition_video_render(obs_source_t *transition, obs_transition_video_render_callback_t callback);
    void obs_transition_video_render2(obs_source_t *transition, obs_transition_video_render_callback_t callback, gs_texture_t *placeholder_texture);
    bool obs_transition_video_render_direct(obs_source_t *transition, enum obs_transition_target target);
    void obs_view_destroy(obs_view_t *view);
    void obs_view_enum_video_info(obs_view_t *view, bool (*enum_proc)(void *, struct obs_video_info *), void *param);
    void obs_view_remove(obs_view_t *view);
    void obs_view_render(obs_view_t *view);
    void obs_view_set_source(obs_view_t *view, uint32_t channel, obs_source_t *source);
    bool obs_wait_for_destroy_queue(void);
    void obs_weak_canvas_addref(obs_weak_canvas_t *weak);
    void obs_weak_canvas_release(obs_weak_canvas_t *weak);
    void obs_weak_encoder_addref(obs_weak_encoder_t *weak);
    bool obs_weak_encoder_references_encoder(obs_weak_encoder_t *weak, obs_encoder_t *encoder);
    void obs_weak_encoder_release(obs_weak_encoder_t *weak);
    void obs_weak_object_addref(obs_weak_object_t *weak);
    bool obs_weak_object_expired(obs_weak_object_t *weak);
    bool obs_weak_object_references_object(obs_weak_object_t *weak, obs_object_t *object);
    void obs_weak_object_release(obs_weak_object_t *weak);
    void obs_weak_output_addref(obs_weak_output_t *weak);
    bool obs_weak_output_references_output(obs_weak_output_t *weak, obs_output_t *output);
    void obs_weak_output_release(obs_weak_output_t *weak);
    void obs_weak_service_addref(obs_weak_service_t *weak);
    bool obs_weak_service_references_service(obs_weak_service_t *weak, obs_service_t *service);
    void obs_weak_service_release(obs_weak_service_t *weak);
    void obs_weak_source_addref(obs_weak_source_t *weak);
    bool obs_weak_source_expired(obs_weak_source_t *weak);
    bool obs_weak_source_references_source(obs_weak_source_t *weak, obs_source_t *source);
    void obs_weak_source_release(obs_weak_source_t *weak);
    void proc_handler_add(proc_handler_t *handler, const char *decl_string, proc_handler_proc_t proc, void *data);
    bool proc_handler_call(proc_handler_t *handler, const char *name, calldata_t *params);
    void proc_handler_destroy(proc_handler_t *handler);
    bool signal_handler_add(signal_handler_t *handler, const char *signal_decl);
    void signal_handler_connect_global(signal_handler_t *handler, global_signal_callback_t callback, void *data);
    void signal_handler_connect_ref(signal_handler_t *handler, const char *signal, signal_callback_t callback, void *data);
    void signal_handler_disconnect_global(signal_handler_t *handler, global_signal_callback_t callback, void *data);
    void signal_handler_remove_current(void);
    void signal_handler_signal(signal_handler_t *handler, const char *signal, calldata_t *params);
    bool video_output_active(const video_t *video);
    void video_output_close(video_t *video);
    bool video_output_connect(video_t *video, const struct video_scale_info *conversion, void (*callback)(void *param, struct video_data *frame), void *param);
    bool video_output_connect2(video_t *video, const struct video_scale_info *conversion, uint32_t frame_rate_divisor, void (*callback)(void *param, struct video_data *frame), void *param);
    void video_output_disconnect(video_t *video, void (*callback)(void *param, struct video_data *frame), void *param);
    bool video_output_disconnect2(video_t *video, void (*callback)(void *param, struct video_data *frame), void *param);
    enum video_format video_output_get_format(const video_t *video);
    double video_output_get_frame_rate(const video_t *video);
    uint64_t video_output_get_frame_time(const video_t *video);
    uint32_t video_output_get_height(const video_t *video);
    uint32_t video_output_get_skipped_frames(const video_t *video);
    uint32_t video_output_get_total_frames(const video_t *video);
    uint32_t video_output_get_width(const video_t *video);
    bool video_output_lock_frame(video_t *video, struct video_frame *frame, int count, uint64_t timestamp);
    int video_output_open(video_t **video, struct video_output_info *info);
    void video_output_stop(video_t *video);
    bool video_output_stopped(video_t *video);
    void video_output_unlock_frame(video_t *video);
"""

STUB_DECLS = """
    void audio_output_get_info(void);
    void gs_create_texture_file_data(void);
    void gs_create_texture_file_data2(void);
    void gs_create_texture_file_data3(void);
    void gs_cubetexture_create(void);
    void gs_duplicator_create(void);
    void gs_duplicator_get_texture(void);
    void gs_effect_create(void);
    void gs_effect_create_from_file(void);
    void gs_effect_get_current_technique(void);
    void gs_effect_get_default_val(void);
    void gs_effect_get_param_by_idx(void);
    void gs_effect_get_param_by_name(void);
    void gs_effect_get_technique(void);
    void gs_effect_get_val(void);
    void gs_effect_get_viewproj_matrix(void);
    void gs_effect_get_world_matrix(void);
    void gs_get_context(void);
    void gs_get_device_name(void);
    void gs_get_device_obj(void);
    void gs_get_driver_version(void);
    void gs_get_effect(void);
    void gs_get_input(void);
    void gs_get_pixel_shader(void);
    void gs_get_render_target(void);
    void gs_get_renderer(void);
    void gs_get_vertex_shader(void);
    void gs_get_zstencil_target(void);
    void gs_indexbuffer_create(void);
    void gs_indexbuffer_get_data(void);
    void gs_param_get_annotation_by_idx(void);
    void gs_param_get_annotation_by_name(void);
    void gs_pixelshader_create(void);
    void gs_pixelshader_create_from_file(void);
    void gs_render_save(void);
    void gs_samplerstate_create(void);
    void gs_shader_get_param_by_idx(void);
    void gs_shader_get_param_by_name(void);
    void gs_shader_get_viewproj_matrix(void);
    void gs_shader_get_world_matrix(void);
    void gs_stagesurface_create(void);
    void gs_stagesurface_create_nv12(void);
    void gs_stagesurface_create_p010(void);
    void gs_swapchain_create(void);
    void gs_technique_get_pass_by_idx(void);
    void gs_technique_get_pass_by_name(void);
    void gs_texrender_create(void);
    void gs_texrender_get_texture(void);
    void gs_texture_create(void);
    void gs_texture_create_from_file(void);
    void gs_texture_create_gdi(void);
    void gs_texture_get_dc(void);
    void gs_texture_get_obj(void);
    void gs_texture_open_nt_shared(void);
    void gs_texture_open_shared(void);
    void gs_texture_wrap_obj(void);
    void gs_timer_create(void);
    void gs_timer_range_create(void);
    void gs_vertexbuffer_create(void);
    void gs_vertexbuffer_get_data(void);
    void gs_vertexshader_create(void);
    void gs_vertexshader_create_from_file(void);
    void gs_voltexture_create(void);
    void gs_zstencil_create(void);
    void obs_avc_find_startcode(void);
    void obs_canvas_create(void);
    void obs_canvas_create_private(void);
    void obs_canvas_get_channel(void);
    void obs_canvas_get_name(void);
    void obs_canvas_get_ref(void);
    void obs_canvas_get_scene_by_name(void);
    void obs_canvas_get_signal_handler(void);
    void obs_canvas_get_source_by_name(void);
    void obs_canvas_get_uuid(void);
    void obs_canvas_get_video(void);
    void obs_canvas_get_weak_canvas(void);
    void obs_canvas_scene_create(void);
    void obs_data_create_from_json_file_safe(void);
    void obs_data_get_autoselect_array(void);
    void obs_data_get_autoselect_obj(void);
    void obs_data_get_autoselect_string(void);
    void obs_data_get_default_array(void);
    void obs_data_get_defaults(void);
    void obs_data_get_json_pretty_with_defaults(void);
    void obs_data_get_json_with_defaults(void);
    void obs_data_get_last_json(void);
    void obs_data_item_byname(void);
    void obs_data_item_get_array(void);
    void obs_data_item_get_autoselect_array(void);
    void obs_data_item_get_autoselect_obj(void);
    void obs_data_item_get_autoselect_string(void);
    void obs_data_item_get_default_array(void);
    void obs_data_item_get_default_obj(void);
    void obs_data_item_get_default_string(void);
    void obs_data_item_get_obj(void);
    void obs_data_item_get_string(void);
    void obs_enable_source_type(void);
    void obs_encoder_create_rerouted(void);
    void obs_encoder_get_defaults(void);
    void obs_encoder_get_last_error(void);
    void obs_encoder_get_module(void);
    void obs_encoder_get_type_data(void);
    void obs_encoder_get_weak_encoder(void);
    void obs_encoder_group_create(void);
    void obs_encoder_parent_video(void);
    void obs_encoder_properties(void);
    void obs_find_module_file(void);
    void obs_get_base_effect(void);
    void obs_get_canvas_by_name(void);
    void obs_get_canvas_by_uuid(void);
    void obs_get_disabled_module(void);
    void obs_get_encoder_by_name(void);
    void obs_get_encoder_codec(void);
    void obs_get_latest_input_type_id(void);
    void obs_get_main_canvas(void);
    void obs_get_main_texture(void);
    void obs_get_module(void);
    void obs_get_module_author(void);
    void obs_get_module_binary_path(void);
    void obs_get_module_data_path(void);
    void obs_get_module_description(void);
    void obs_get_module_file_name(void);
    void obs_get_module_id(void);
    void obs_get_module_lib(void);
    void obs_get_module_name(void);
    void obs_get_module_version(void);
    void obs_get_output_by_name(void);
    void obs_get_output_supported_audio_codecs(void);
    void obs_get_output_supported_video_codecs(void);
    void obs_get_private_data(void);
    void obs_get_profiler_name_store(void);
    void obs_get_service_by_name(void);
    void obs_group_from_source(void);
    void obs_hotkey_binding_get_hotkey(void);
    void obs_hotkey_get_registerer(void);
    void obs_hotkeys_save_encoder(void);
    void obs_hotkeys_save_output(void);
    void obs_hotkeys_save_service(void);
    void obs_hotkeys_save_source(void);
    void obs_load_canvas(void);
    void obs_missing_file_create(void);
    void obs_missing_file_get_path(void);
    void obs_missing_file_get_source_name(void);
    void obs_missing_files_create(void);
    void obs_missing_files_get_file(void);
    void obs_module_get_config_path(void);
    void obs_module_get_locale_text(void);
    void obs_module_load_locale(void);
    void obs_nal_find_startcode(void);
    void obs_obj_get_data(void);
    void obs_obj_get_id(void);
    void obs_object_get_ref(void);
    void obs_object_get_weak_object(void);
    void obs_output_audio(void);
    void obs_output_defaults(void);
    void obs_output_get_module(void);
    void obs_output_get_proc_handler(void);
    void obs_output_get_protocols(void);
    void obs_output_get_supported_audio_codecs(void);
    void obs_output_get_supported_video_codecs(void);
    void obs_output_get_type_data(void);
    void obs_output_get_video_conversion(void);
    void obs_output_get_video_encoder2(void);
    void obs_output_get_weak_output(void);
    void obs_output_properties(void);
    void obs_output_video(void);
    void obs_properties_add_bool(void);
    void obs_properties_add_button(void);
    void obs_properties_add_button2(void);
    void obs_properties_add_color(void);
    void obs_properties_add_color_alpha(void);
    void obs_properties_add_editable_list(void);
    void obs_properties_add_float(void);
    void obs_properties_add_float_slider(void);
    void obs_properties_add_font(void);
    void obs_properties_add_frame_rate(void);
    void obs_properties_add_group(void);
    void obs_properties_add_int(void);
    void obs_properties_add_int_slider(void);
    void obs_properties_add_list(void);
    void obs_properties_add_path(void);
    void obs_properties_add_text(void);
    void obs_properties_create(void);
    void obs_properties_create_param(void);
    void obs_properties_get_param(void);
    void obs_properties_get_parent(void);
    void obs_property_button_url(void);
    void obs_property_editable_list_default_path(void);
    void obs_property_editable_list_filter(void);
    void obs_property_frame_rate_option_description(void);
    void obs_property_frame_rate_option_name(void);
    void obs_property_group_content(void);
    void obs_save_canvas(void);
    void obs_scene_add_group2(void);
    void obs_scene_find_sceneitem_by_id(void);
    void obs_scene_find_source_recursive(void);
    void obs_scene_get_group(void);
    void obs_scene_insert_group2(void);
    void obs_scene_save_transform_states(void);
    void obs_sceneitem_get_group(void);
    void obs_sceneitem_get_transition(void);
    void obs_sceneitem_transition_save(void);
    void obs_service_create_private(void);
    void obs_service_get_connect_info(void);
    void obs_service_get_module(void);
    void obs_service_get_preferred_output_type(void);
    void obs_service_get_protocol(void);
    void obs_service_get_supported_audio_codecs(void);
    void obs_service_get_supported_video_codecs(void);
    void obs_service_get_type(void);
    void obs_service_get_type_data(void);
    void obs_service_get_weak_service(void);
    void obs_service_properties(void);
    void obs_source_duplicate(void);
    void obs_source_get_canvas(void);
    void obs_source_get_frame(void);
    void obs_source_get_missing_files(void);
    void obs_source_get_module(void);
    void obs_source_get_proc_handler(void);
    void obs_source_get_type_data(void);
    void obs_source_get_unversioned_id(void);
    void obs_source_get_weak_source(void);
    void obs_view_add(void);
    void obs_view_add2(void);
    void obs_view_create(void);
    void obs_view_get_source(void);
    void obs_weak_canvas_get_canvas(void);
    void obs_weak_encoder_get_encoder(void);
    void obs_weak_object_get_object(void);
    void obs_weak_output_get_output(void);
    void obs_weak_service_get_service(void);
    void obs_weak_source_get_source(void);
    void proc_handler_create(void);
    void video_output_get_info(void);
"""
